### ISSUE TITLE
questions aoubt “error loading file”

### ISSUE THREAD

**Issue by dengnan0819** [Shawdox/Reproduce-for-GREBE#1]
你好，请教应如何解决错误日志中的第四个问题：

问题4：在使用analyer时报错：

/home/wx/Shaw/GREBE/analyzer/build/lib/analyzer：加载文件“./case/linux-bitcode/lib/dump_stack.c.bc”时出错

解决方法：

问题定位到KAMain.cc文件使用ParseIR()函数解析bc文件：

**Comment by Lelouny** [comment]
你好，请问你最后选择了哪个内核版本可以成功复现呢
